create extension if not exists pgcrypto;

create table if not exists checklists(
  id bigint primary key,
  csv_id bigint unique,
  unidade text,
  categoria text,
  momento text,
  frequencia text,
  horario_previsto text,
  responsavel_sugerido text,
  obrigatorio boolean,
  anexo_manual boolean,
  foto_ambiente boolean,
  campo_aberto text
);

create table if not exists checklist_items(
  id bigint generated by default as identity primary key,
  checklist_id bigint references checklists(id) on delete cascade,
  item_nome text not null,
  tipo_resposta text,
  foto_obrigatoria boolean default false,
  obrigatorio boolean default true,
  ordem integer,
  observacao text
);

create table if not exists submissions(
  id uuid primary key default gen_random_uuid(),
  checklist_id bigint references checklists(id),
  checklist_name text,
  operator_name text not null,
  unidade text not null,
  date date not null,
  filled_at timestamptz not null default now(),
  status text not null,
  has_problem boolean default false,
  observacoes text,
  oknok text,
  passagem text,
  responses_json jsonb default '{}'::jsonb
);
alter table submissions add column if not exists checklist_name text;
alter table submissions add column if not exists responses_json jsonb default '{}'::jsonb;

create table if not exists submission_item_responses(
  id uuid primary key default gen_random_uuid(),
  submission_id uuid references submissions(id) on delete cascade,
  checklist_item text,
  response_value text
);

create table if not exists submission_files(
  id uuid primary key default gen_random_uuid(),
  submission_id uuid references submissions(id) on delete cascade,
  checklist_item text,
  file_name text,
  file_path text,
  file_type text
);
alter table submission_files add column if not exists checklist_item text;

create table if not exists maintenance_records(
  id uuid primary key default gen_random_uuid(),
  submission_id uuid references submissions(id) on delete cascade,
  date date,
  unidade text,
  checklist_origem text,
  area_praca text,
  item_problema text,
  descricao_problema text,
  responsible text,
  criticidade text,
  status text,
  prazo_retorno text,
  observacoes text
);

insert into checklists (id, csv_id, unidade, categoria, momento, frequencia, horario_previsto, responsavel_sugerido, obrigatorio, anexo_manual, foto_ambiente, campo_aberto) values
(101,101,'Delivery','ABERTURA','Manhã','Diária','Até 10h30','Líder de turno',true,false,false,false),
(102,102,'Delivery','TROCA DE TURNO','Tarde','Diária','14h40 às 16h20','Líder de turno',true,false,false,false),
(103,103,'Delivery','FECHAMENTO','Noite','Diária','22h às 23h30','Líder de turno',true,false,false,false),
(104,104,'Delivery','MANUTENÇÃO','Conforme sinalização','Diária','Conforme sinalização','Líder de turno',true,false,true,true)
on conflict (id) do update set categoria=excluded.categoria, horario_previsto=excluded.horario_previsto;

alter table checklists enable row level security;
alter table checklist_items enable row level security;
alter table submissions enable row level security;
alter table submission_item_responses enable row level security;
alter table submission_files enable row level security;
alter table maintenance_records enable row level security;

do $$ begin create policy "public checklists" on checklists for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public checklist_items" on checklist_items for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public submissions" on submissions for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public submission_item_responses" on submission_item_responses for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public submission_files" on submission_files for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public maintenance" on maintenance_records for all using (true) with check (true); exception when duplicate_object then null; end $$;
