import Papa from 'papaparse';
import { useEffect, useMemo, useState } from 'react';
import csvRaw from '../data/checklists_delivery_mvp.csv?raw';

const maintenanceTriggers = ['Abertura da casa','Checagem de temperatura 1','Troca de turno','Checagem de temperatura 2','Fechamento da casa'];
const storageKey = 'notorious-submissions-v1';
const mKey = 'notorious-maintenance-v1';
const read=(k)=>JSON.parse(localStorage.getItem(k)||'[]');
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10);
const parseCsv=()=>Papa.parse(csvRaw,{header:true,delimiter:';'}).data.filter(r=>r.ID);
const deadlineText=(h)=>h||'Conforme rotina';
const status=(c,subs)=>{const s=subs.find(x=>x.checklistId===c.ID&&x.date===today()); if(s) return s.hasProblem?'Com problema':'Preenchido'; return 'Pendente';};

function ChecklistForm({check,onClose,onSave,operator}){const [f,setF]=useState({observacoes:'',oknok:'OK',passagem:'',hasProblem:'Não'}); const [files,setFiles]=useState({manual:null,foto:null}); const [m,setM]=useState({area:'',item:'',descricao:'',criticidade:'Média',status:'Aberto',prazo:'',observacoes:''});
const needsManual=check['Anexo ficha manual?']==='Sim'; const needsPhoto=check['Foto ambiente?']==='Sim'; const needsText=check.Categoria==='Troca de turno'; const needsOknok=check.Categoria.includes('Checklist de praça')||check.Categoria.includes('Limpeza');
const valid=(!needsManual||files.manual)&&(!needsPhoto||files.foto)&&(!needsText||f.passagem.trim())&&operator.trim();
return <div className='modal'><div className='card'><h3>{check.Categoria}</h3><input type='time' defaultValue={new Date().toTimeString().slice(0,5)} readOnly/><p>Responsável: <b>{operator}</b></p>{needsOknok&&<select onChange={e=>setF({...f,oknok:e.target.value})}><option>OK</option><option>NOK</option><option>Conforme</option><option>Não conforme</option></select>}{needsText&&<textarea placeholder='Pendências e avisos' onChange={e=>setF({...f,passagem:e.target.value})}/>}<textarea placeholder='Observações (opcional)' onChange={e=>setF({...f,observacoes:e.target.value})}/>{needsManual&&<input type='file' accept='image/*,.pdf' onChange={e=>setFiles({...files,manual:e.target.files?.[0]?.name})}/>}<input type='file' accept='image/*,.pdf' onChange={e=>setFiles({...files,foto:e.target.files?.[0]?.name})}/><label>Há problema?</label><select onChange={e=>setF({...f,hasProblem:e.target.value})}><option>Não</option><option>Sim</option></select>{f.hasProblem==='Sim'&&maintenanceTriggers.includes(check.Categoria)&&<div><h4>Manutenção</h4><input placeholder='Área/Praça' onChange={e=>setM({...m,area:e.target.value})}/><input placeholder='Item com problema' onChange={e=>setM({...m,item:e.target.value})}/><textarea placeholder='Descrição' onChange={e=>setM({...m,descricao:e.target.value})}/><select onChange={e=>setM({...m,criticidade:e.target.value})}><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select></div>}<button disabled={!valid} onClick={()=>onSave({check,f,files,m})}>Finalizar</button><button onClick={onClose}>Cancelar</button></div></div>;
}

export function FillPage(){const [operator,setOperator]=useState(localStorage.getItem('operator')||'');const [checklists]=useState(parseCsv()); const [subs,setSubs]=useState(read(storageKey)); const [active,setActive]=useState();
const ordered=useMemo(()=>[...checklists].sort((a,b)=>a.ID-b.ID),[checklists]);
const save=({check,f,files,m})=>{const submission={id:crypto.randomUUID(),checklistId:check.ID,checklist:check.Categoria,momento:check.Momento,frequency:check['Frequência'],deadline:check['Horário previsto'],operator,date:today(),filledAt:new Date().toISOString(),status:f.hasProblem==='Sim'?'Com problema':'Preenchido',hasProblem:f.hasProblem==='Sim',observacoes:f.observacoes,oknok:f.oknok,passagem:f.passagem,files:[files.manual,files.foto].filter(Boolean),unit:'Delivery'}; const next=[...subs.filter(s=>!(s.checklistId===check.ID&&s.date===today())),submission]; setSubs(next); write(storageKey,next); if(submission.hasProblem&&maintenanceTriggers.includes(check.Categoria)){const mm=[...read(mKey),{id:crypto.randomUUID(),submissionId:submission.id,date:today(),unit:'Delivery',checklist:check.Categoria,responsible:operator,...m}]; write(mKey,mm);} setActive(null);};
useEffect(()=>localStorage.setItem('operator',operator),[operator]);
return <main><h1>Checklist do Dia - Delivery</h1><p><a href='/preenchimento'>Acessar preenchimento</a> · <a href='/admin'>Acessar painel admin</a></p><input placeholder='Nome do Líder de Turno' value={operator} onChange={e=>setOperator(e.target.value)} required/>{ordered.map(c=>{const st=status(c,subs);return <article key={c.ID} className={`card ${st}`}><h3>{c.Categoria}</h3><p>{c.Momento} · {c['Frequência']}</p><p><b>Limite:</b> {deadlineText(c['Horário previsto'])}</p><p><b>Responsável sugerido:</b> {c['Responsável sugerido']||'-'}</p><span>{st}</span><button disabled={!operator.trim()} onClick={()=>setActive(c)}>{st==='Preenchido'||st==='Com problema'?'Visualizar envio':'Preencher'}</button></article>})}{active&&<ChecklistForm check={active} operator={operator} onClose={()=>setActive(null)} onSave={save}/>}</main>;}

export function AdminPage(){const [subs,setSubs]=useState(read(storageKey)); const [manu,setManu]=useState(read(mKey)); const [f,setF]=useState({date:'',checklist:'',responsible:'',status:''});
useEffect(()=>{setSubs(read(storageKey));setManu(read(mKey));},[]);
const data=subs.filter(s=>(!f.date||s.date===f.date)&&(!f.checklist||s.checklist===f.checklist)&&(!f.responsible||s.operator.includes(f.responsible))&&(!f.status||s.status===f.status));
const exportCsv=()=>{const rows=['data,horario_previsto,horario_preenchimento,checklist,momento,responsavel,status,problema,observacoes,anexos'];data.forEach(r=>rows.push([r.date,r.deadline,r.filledAt,r.checklist,r.momento,r.operator,r.status,r.hasProblem?'Sim':'Não',`"${(r.observacoes||'').replaceAll('"','""')}"`,r.files.join('|')].join(','))); const blob=new Blob([rows.join('\n')]); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='historico_checklists.csv'; a.click();};
return <main><h1>Painel Administrativo</h1><p><a href='/preenchimento'>Acessar preenchimento</a> · <a href='/admin'>Acessar painel admin</a></p><section className='grid'><div>Total previstos: 8</div><div>Total preenchido: {subs.length}</div><div>Com problema: {subs.filter(s=>s.hasProblem).length}</div><div>Pendentes: {Math.max(8-subs.length,0)}</div></section><section><h2>Filtros</h2><input type='date' onChange={e=>setF({...f,date:e.target.value})}/><input placeholder='Responsável' onChange={e=>setF({...f,responsible:e.target.value})}/><button onClick={exportCsv}>Exportar CSV</button></section><table><thead><tr><th>Data</th><th>Checklist</th><th>Responsável</th><th>Status</th><th>Anexos</th></tr></thead><tbody>{data.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.checklist}</td><td>{r.operator}</td><td>{r.status}</td><td>{r.files.map(x=><span key={x}>{x} </span>)}</td></tr>)}</tbody></table><h2>Manutenções abertas</h2>{manu.filter(m=>m.status!=='Resolvido').map(m=><article key={m.id} className='card'><b>{m.checklist}</b><p>{m.item} - {m.descricao}</p><p>{m.status} · {m.criticidade}</p></article>)}</main>;}
